language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3.5

install:
  - pip install tox twine wheel python-coveralls

script:
  - echo $TRAVIS_PYTHON_VERSION
  - export PYVER=`echo $TRAVIS_PYTHON_VERSION | tr "." "\n" | head -n 1`
  - echo $PYVER
  - tox -e py$PYVER

jobs:
  include:
    - stage: package
      python: 3.6
      script:
      - python setup.py bdist_wheel
      # Uncomment this line to enable automatic publishing to pypi.org
      # - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS

after_success:
  - coveralls
